### ISSUE TITLE
Solve those exercises

### ISSUE THREAD

**Issue by Olivierhub04** [Olivierhub04/Internship#1]
Solve all the exercises

**Comment by Jeff-Clinton** [comment]
Ok sirSent from my Huawei phone-------- Original Message --------Subject: Re: [Olivierhub04/Internship] Solve those exercises (Issue #1)From: Olivierhub04 To: Olivierhub04/Internship CC: Jeff-Clinton ,Assign 
Assigned #1 to @Jeff-Clinton.

**Comment by Olivierhub04** [comment]
@NguSmith2004 Nice work, but don't forget before doing any modelling make sure to identify all the available entities and also all the implied and derived ones. Your main focus should be on ER-diagram.

**Comment by Olivierhub04** [comment]
@Jeff-Clinton I really appreciate your understanding of these core concepts, nevertheless you will have to put in more efforts while designing class diagram make sure to depict all the possible classes same for er-diagram. Good use case diagram.

**Comment by Olivierhub04** [comment]
@Kandy-541 great work, nevertheless work harder on your class diagram understanding

**Comment by Olivierhub04** [comment]
@Philemon-COT needs to further your understanding of class diagram and er-diagram, meet me for more details.
